### ISSUE TITLE
Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by MONKATRON** [ZenSoftware/zen#13]
Cloned Repo and followed the steps in the Readme - Angular portal runs but nothing in the page loads and console receives the message "Uncaught SyntaxError: Unexpected token e in JSON at position 0".

**Comment by ZenSoftware** [comment]
Hmm, unfortunately I have not been able to reproduce this error and have not encountered it before.  May I ask what operating system you are on?  Did you install your packages with NPM?  I have found issues when using Yarn.  I would be happy to help, but I need more information.

**Comment by MONKATRON** [comment]
Looks to be a chrome issue with an addon - weirdly works fine in incognito mode but not in regular with all addons dissabled.

**Comment by ZenSoftware** [comment]
Ah ok!  I'm glad everything is compiling correctly.  Do let me know how the starter kit works out for your project.  Cheers my friend 🥂
