### ISSUE TITLE
Running the steps on README.md ends up in error

### ISSUE THREAD

**Issue by relivvius** [ZenSoftware/zen#28]
> nx serve api

 >  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

node -v:
v20.5.0

npm -v
9.8.0

**Comment by ZenSoftware** [comment]
Hello.  Oh geeze, I haven't seen that one before.  Let me startup a clean git clone and see what I discover.  I'll let you know what I find.

**Comment by ZenSoftware** [comment]
Ok, so I see in the Nrwl Nx repo that people submitted a couple of issues with regards to this error message.  I am getting it as well utilizing NPM.  Though, everything seems to be working fine if I utilize PNPM as the package manager.

I'll keep working on this.  But for now, the best thing to do would be to install PNPM and utilize that to install the `node_modules` folder.

You can find instructions of how to install PNPM here: https://pnpm.io/installation

**Comment by ZenSoftware** [comment]
I just pushed out an update making pnpm a requirement until this issue is resolved.  I also updated all the projects dependencies to the latest compatible versions.  You'll want to pull the latest changes and follow the new README.md instructions.
