### ISSUE TITLE
Update localstorage-slim to version 2.5.0 for debugging and addressing potential issues

### ISSUE THREAD

**Issue by LennonReid** [ZenSoftware/zen#31]
I've noticed that if the "token" value pre-exists in the default host localhost:4200 before running the project, it can lead to a syntax error during JSON parsing by a dependency library. I contacted the team behind the localstorege-slim library regarding this, and they were quick to address it. They've released a new version, 2.5.0, just yesterday. For more details, refer to the related [issue](https://github.com/digitalfortress-tech/localstorage-slim/issues/25).

If it's alright with you, I'd happily submit a PR to address this.

BTW, I am blown away by the incredible work you've done! Thanks a million for creating and sharing this code!

**Comment by ZenSoftware** [comment]
Thanks again!  Closing this along with https://github.com/ZenSoftware/zen/pull/32

I was hoping to find some contributors.
