### ISSUE TITLE
Licence, context

### ISSUE THREAD

**Issue by growms** [ZenSoftware/zen#33]
Hello, I'm back here because I really like this project and I think it has some potentials. I would like to know more but I could not find any other way to reach you. So here are some questions : 
- What are the licence on this work ?
- Is it a professional or a personal work ?
- What do you plan to do with this ?
- Are you using it in prod ?
- Are you close to Lennon Reid ?

okay I'M NOT FROM THE POLICE. Just digging a bit because, maybe I could offer some time and eventually use it in some projects of mine.

Cheers

**Comment by ZenSoftware** [comment]
Hello @growms!
You can usually find the license for a project in the `package.json`.  This project is under the MIT license.  Do whatever you wish with it, including for commercial projects for profit.  The project was originally intended for delivering enterprise solutions.  It has everything you need to create a user portal.  This repo is a 3 year old project with consistent updates.  Yes, I have used this tech stack to deliver enterprise solutions in production.  I do not really know Lennon Reid, he just submitted a small pull request not long ago that I accepted.  I've been looking into creating a GitHub wiki to document the project with a better getting started guide and general guidelines of how to best go about common scenarios.  I'm hoping to find more contributors.

I've been meaning to create a Discord channel if this project gained more traction.  For now, here is the best place to communicate about this project.  So no worries at all.  Let me know if you have any more questions.  Cheers!  🎐
